python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_0 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_0 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_1 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_1 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_2 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_2 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_3 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_3 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_4 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_4 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_5 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_5 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_6 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_6 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_7 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_7 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_8 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_8 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_9 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/nerf_d/subset_9 +render_test_views=True