python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_0 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_0 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_1 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_1 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_2 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_2 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_3 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_3 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_4 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_4 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_5 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_5 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_6 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_6 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_7 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_7 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_8 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_8 +render_test_views=True
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_9 +render_test_views=False
python torch_nerf/runners/render.py +log_dir=outputs/vanilla/subset_9 +render_test_views=True